---
title: "R Notebook"
output: html_notebook
---

load packages
```{r}
library(sf)
library(tidyverse)
library(tmap)
library(readr)
library(RSQLite)
library(dplyr)
library(here)
library(janitor)
library(plotly)
library(maptools)
library(RColorBrewer)
library(classInt)
library(sp)
library(rgeos)
library(tmap)
library(tmaptools)
library(fs)
library(rgdal)
library(geojsonio)
library(stringr)
library(plotly)
library(tmaptools)
library(OpenStreetMap)
library(rJava)
library(raster)
library(terra)
```


import data
```{r}
GII_origindata <- read_csv(here::here("data_hw","HDR21-22_Composite_indices_complete_time_series.csv"))

WorldSpatial <- st_read(here::here("data_hw","World_Countries_Generalized","World_Countries_Generalized.shp"))

```
tidy data
```{r}
GII_2010_19 <- GII_origindata[, c("iso3", "country", "hdicode", "region", "gii_2010", "gii_2019")]

GII_2010_19 <- GII_2010_19 %>%
  mutate(., Diff_10_19= gii_2019 - gii_2010)
```

join data
```{r}
Spatial_GII_Joined <- WorldSpatial %>%
  left_join(., GII_2010_19, by = c("COUNTRY" = "country"))

```







